### ISSUE TITLE
How can I get access to the paper?

### ISSUE THREAD

**Issue by 9501sam** [wineslab/colosseum-oran-coloran-dataset#3]
`README.md` says that this dataset is used for the paper M. Polese, L. Bonati, S. D'Oro, S. Basagni, T. Melodia, *"ColoRAN: Design and Testing of Open RAN Intelligence on Large-scale Experimental Platforms," IEEE Transactions on Mobile Computing*, pp. 1-14, July 2022. However, I can't find any paper titled *"ColoRAN: Design and Testing of Open RAN Intelligence on Large-scale Experimental Platforms"* after I search it. I noticed that the same authors publish *"ColO-RAN: Developing Machine Learning-based xApps for Open RAN Closed-loop Control on Programmable Experimental Platforms"* but I also want to study about the paper mentioned in `README.md`. How can I get access to the paper? Thanks.

**Comment by leonardobonati** [comment]
Hi, thank you for spotting this typo in the `README.md` file. This is indeed the paper [ColO-RAN: Developing Machine Learning-based xApps for Open RAN Closed-loop Control on Programmable Experimental Platforms](https://arxiv.org/pdf/2112.09559.pdf). I will fix the typo in the `README.md` file.

**Comment by 9501sam** [comment]
Hi, thank you for your assistance in helping me access the right resources.
