### ISSUE TITLE
How do the files correspond with each other?

### ISSUE THREAD

**Issue by maticpokorn** [wineslab/colosseum-oran-coloran-dataset#6]
Hi!

I can't seem to understand how the .csv files are connected with each other. I presume the BS and UE data are measured on the same time interval, but they all have slightly different lengths, for example a .csv for UE1 could have 50 lines more than a .csv for UE2. Is there any offset involved or do they all start at line 1 and the measurements just stop earlier for some network elements?

Also, how do these files correspond to the files in the directory 'slices_bs{i}'? It looks to me that there are always 6 files in there, 2 for each slice, but how do they connect to the BS and UE files?

In the README.md, under 'UEs belong to different traffic classes' there are UEs with numbers going up to 44, but when I counted them, there are only 40 listed.

**Comment by leonardobonati** [comment]
> I can't seem to understand how the .csv files are connected with each other. I presume the BS and UE data are measured on the same time interval, but they all have slightly different lengths, for example a .csv for UE1 could have 50 lines more than a .csv for UE2. Is there any offset involved or do they all start at line 1 and the measurements just stop earlier for some network elements?

Measurement should start when the UE connects and stop when the UE disconnects. If UEs connect/disconnect at different times, this is likely to happen.

> Also, how do these files correspond to the files in the directory 'slices_bs{i}'? It looks to me that there are always 6 files in there, 2 for each slice, but how do they connect to the BS and UE files?

There are 2 files for each slide since the dataset was run with 2 UEs per slice.

> In the README.md, under 'UEs belong to different traffic classes' there are UEs with numbers going up to 44, but when I counted them, there are only 40 listed.

Sorry, I'm not sure I get what you mean here.

**Comment by maticpokorn** [comment]
Thank you for the clarification! 

In the last point I was referring to this part of the README file:

![ues](https://github.com/wineslab/colosseum-oran-coloran-dataset/assets/106033484/bac7c554-953c-45f0-a625-851731b5d068)

Here there are 40 listed UEs with labels going up to 44 (I guess there are 4 missing), but above you state that there were 42 UEs used when acquiring the dataset. That was not entirely clear to me.

**Comment by leonardobonati** [comment]
This is a typo in the `README.md`, thank you for spotting it. The correct configuration should be the following, you can also verify which user is associated to which slice by looking at the `slice_id` column in the `.csv` files (e.g., file `1010123456002_metrics.csv` would be UE 2, `1010123456003_metrics.csv` UE 3, and so on).

- UEs belong to different traffic classes:
    - eMBB UEs (slice 0): 3, 6, 10, 13, 17, 20, 24, 27, 31, 34, 38, 41, 45, 48
    - MTC UEs (slice 1): 4, 7, 11, 14, 18, 21, 25, 28, 32, 35, 39, 42, 46, 49
    - URLLC UEs (slice 2): 2, 5, 9, 12, 16, 19, 23, 26, 30, 33, 37, 40, 44, 47
 
There should be 7 missing nodes that correspond to the base stations
- BS: 1, 8, 15, 22, 29, 36, 43

I will update the `README.md` accordingly.

**Comment by maticpokorn** [comment]
Ok it makes sense to me now, thanks a lot for all the clarifications!
